# Generated by Django 4.1.2 on 2022-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(max_length=5)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('mobile_no', models.PositiveIntegerField(max_length=10)),
                ('Bgroup', models.CharField(max_length=3)),
            ],
        ),
    ]
