# Generated by Django 4.1.2 on 2022-11-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_age_alter_patient_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
