# Generated by Django 4.1.2 on 2022-10-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood_Donate',
        ),
    ]
