# Generated by Django 4.1.2 on 2022-10-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('Bgroup', models.CharField(max_length=3)),
                ('units', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
